### PR TITLE
Fixed Bugs by updating mods

### PR DESCRIPTION
**Pull request by Ashen-sysadmin**
Hey, Thanks for compiling a fixed version of Blightfall, 

Here is a branch where I updated several of the mods that kept crashing otherwise. (Enderstorage and Tinkers construct). Please consider integrating it into the main branch.

### CODE REVIEW

**Comment by Ashen-sysadmin** [comment]
Thanks for your excellent work.

**Review by leetfin — CHANGES_REQUESTED** [review]
Thanks for the pull request! 
Attempting to load with these changes doesn't launch at all, you've got a few duplicated mods as well as missing EnderStorage here. If you can fix these issues please add another commit doing so to the PR, otherwise let me know and I'll try and fix it this weekend!

**Comment by MerrittK** [comment]
Sorry. I have the working folder to send over tomorrow.

**Comment by MerrittK** [comment]
I missed the notification at first. The config I am using works for our server.

**Comment by Ashen-sysadmin** [comment]
Updated fork. Thanks for your time and patience. We are using your base code for our server. What we have now should hopefully work.

**Comment by leetfin** [comment]
Merged, thanks!

**Pull request merged**
